version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  render-front:
    lang: golang-middleware
    handler: ./render-front
    image: zephyr75/render-front:latest
    annotations:
          com.openfaas.timeout: "1000s"
    environment:
      BACK_URL: "http://34.55.252.22:8080/function/render"
